language: php
dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
matrix:
    include:
      - php: "5.3"
        dist: precise
    allow_failures:
      - php: hhvm    

install:
  - composer install --no-interaction
script:
  - mkdir -p cache
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v